<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Lengkapi Info Akun_img-thumbnail img-av_2cc814</name>
   <tag></tag>
   <elementGuidId>1743d241-cf31-4e4d-8d90-699f5ba94b60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img-thumbnail.img-avatar-profile.rounded-4.p-0.border-0.overflow-hidden</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='form-avatar-image']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6015a468-28ad-4845-aaec-5b2d43fefa1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-thumbnail img-avatar-profile rounded-4 p-0 border-0 overflow-hidden</value>
      <webElementGuid>dfbfefdc-cc14-4778-a1dd-ff59c298a117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://secondhand.binaracademy.org/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdEV3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fa4927a607f51975bbadf512a9c07d8318aa057f/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2RkhKbGMybDZaVjkwYjE5c2FXMXBkRnNIYVFLUUFXa0NrQUU9IiwiZXhwIjpudWxsLCJwdXIiOiJ2YXJpYXRpb24ifX0=--68ce5b37660f0527e00bd1e60af75a7b48156984/discussion-rubber-stamp-discussion-rubber-stamp-grunge-design-dust-scratches-effects-can-be-easily-removed-clean-crisp-102004323.jpg</value>
      <webElementGuid>d501704e-b5dc-4938-b677-c1709a23ea22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-avatar-image&quot;)/img[@class=&quot;img-thumbnail img-avatar-profile rounded-4 p-0 border-0 overflow-hidden&quot;]</value>
      <webElementGuid>bea90a75-0ed2-4b88-93b1-73e8beaa9436</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-avatar-image']/img</value>
      <webElementGuid>13e12b5a-07f4-4fa2-9689-9fc79c354c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://secondhand.binaracademy.org/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdEV3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fa4927a607f51975bbadf512a9c07d8318aa057f/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2RkhKbGMybDZaVjkwYjE5c2FXMXBkRnNIYVFLUUFXa0NrQUU9IiwiZXhwIjpudWxsLCJwdXIiOiJ2YXJpYXRpb24ifX0=--68ce5b37660f0527e00bd1e60af75a7b48156984/discussion-rubber-stamp-discussion-rubber-stamp-grunge-design-dust-scratches-effects-can-be-easily-removed-clean-crisp-102004323.jpg')]</value>
      <webElementGuid>09d099d0-4cd3-4030-9704-aa35dde7b524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>0ef59122-7b92-4590-b1dc-7845d7935388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://secondhand.binaracademy.org/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdEV3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fa4927a607f51975bbadf512a9c07d8318aa057f/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2RkhKbGMybDZaVjkwYjE5c2FXMXBkRnNIYVFLUUFXa0NrQUU9IiwiZXhwIjpudWxsLCJwdXIiOiJ2YXJpYXRpb24ifX0=--68ce5b37660f0527e00bd1e60af75a7b48156984/discussion-rubber-stamp-discussion-rubber-stamp-grunge-design-dust-scratches-effects-can-be-easily-removed-clean-crisp-102004323.jpg']</value>
      <webElementGuid>8a84e224-9e74-4f33-b0f1-5def043dd301</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
