<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Lengkapi Info Akun_img-thumbnail img-av_2cc814</name>
   <tag></tag>
   <elementGuidId>1743d241-cf31-4e4d-8d90-699f5ba94b60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img-thumbnail.img-avatar-profile.rounded-4.p-0.border-0.overflow-hidden</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='form-avatar-image']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9bb6b447-0d68-447d-b33f-336dddc8a37d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-thumbnail img-avatar-profile rounded-4 p-0 border-0 overflow-hidden</value>
      <webElementGuid>03a9c6f5-53e4-49a8-90ad-ae2ae8d94b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://secondhand.binaracademy.org/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdlF3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--693ead666140d5051860d7cffbf9c638de385bf3/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBPZ2h3Ym1jNkZISmxjMmw2WlY5MGIxOXNhVzFwZEZzSGFRS1FBV2tDa0FFPSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--5f30ffda9be2b78c328f306bddb735fb92367c7b/shutterstock_344519003.png</value>
      <webElementGuid>9892a920-72b2-4687-a269-754e83598d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-avatar-image&quot;)/img[@class=&quot;img-thumbnail img-avatar-profile rounded-4 p-0 border-0 overflow-hidden&quot;]</value>
      <webElementGuid>2f4686c3-0e02-4fc7-9b14-5b704dafe94d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-avatar-image']/img</value>
      <webElementGuid>dd59c068-5754-4ca0-a6bb-8f0875ba7617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://secondhand.binaracademy.org/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdlF3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--693ead666140d5051860d7cffbf9c638de385bf3/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBPZ2h3Ym1jNkZISmxjMmw2WlY5MGIxOXNhVzFwZEZzSGFRS1FBV2tDa0FFPSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--5f30ffda9be2b78c328f306bddb735fb92367c7b/shutterstock_344519003.png')]</value>
      <webElementGuid>21b5043c-b751-4025-ba23-938d3adaca8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>1cc9b0b7-a66e-42e7-9d06-f4f7b5b67cfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://secondhand.binaracademy.org/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdlF3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--693ead666140d5051860d7cffbf9c638de385bf3/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBPZ2h3Ym1jNkZISmxjMmw2WlY5MGIxOXNhVzFwZEZzSGFRS1FBV2tDa0FFPSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--5f30ffda9be2b78c328f306bddb735fb92367c7b/shutterstock_344519003.png']</value>
      <webElementGuid>76b01792-5167-4f89-b655-1b35a02ceba1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
