<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih KotaSoloJogjaJakartaBandungSemarang</name>
   <tag></tag>
   <elementGuidId>fc820ee2-f8c3-446b-b388-cc666b7251ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_city_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='user_city_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>37af11ed-cdf6-4b5a-a2ef-419cd76ffd54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select rounded-4 p-3</value>
      <webElementGuid>82bafd87-a23a-4611-acf5-7d278f83cbf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>faa327ec-0f83-42ae-9712-bb87a70d6770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user[city_id]</value>
      <webElementGuid>8dd39eb3-4f82-40cb-b862-130484c4bd63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_city_id</value>
      <webElementGuid>2639266f-8ab9-4fd4-b729-bf75915e65b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Kota
Solo
Jogja
Jakarta
Bandung
Semarang</value>
      <webElementGuid>6d31bb38-2ac2-46f0-9734-7cdce18bbbea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_city_id&quot;)</value>
      <webElementGuid>75ff8572-34ca-4c83-88c8-1def3fd0a345</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='user_city_id']</value>
      <webElementGuid>bf7f3a05-50a1-4a5f-b7b6-5e7f540cee97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kota'])[1]/following::select[1]</value>
      <webElementGuid>9f901733-d9f5-4c48-9694-5c123c2a04c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama'])[1]/following::select[1]</value>
      <webElementGuid>0c1e2414-eff9-43e0-bc87-bee266696b98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat'])[1]/preceding::select[1]</value>
      <webElementGuid>f44a3ee1-d299-434a-9e7d-32e81774ed3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jl. Jalan II'])[1]/preceding::select[1]</value>
      <webElementGuid>b26a6b50-92a5-4c44-bf1b-8a73697f09d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>5688bfe4-430b-494e-aa39-7d0ea82e0166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'user[city_id]' and @id = 'user_city_id' and (text() = 'Pilih Kota
Solo
Jogja
Jakarta
Bandung
Semarang' or . = 'Pilih Kota
Solo
Jogja
Jakarta
Bandung
Semarang')]</value>
      <webElementGuid>b1cf6855-8a61-4c51-9607-3511ab18b11b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
