<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih KotaSoloJogjaJakartaBandungSemarang</name>
   <tag></tag>
   <elementGuidId>fc820ee2-f8c3-446b-b388-cc666b7251ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_city_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='user_city_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>735294cf-efd9-4ac7-afe8-b8a39f218f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select rounded-4 p-3</value>
      <webElementGuid>1bb64ddd-3723-43bb-bc66-0bda0e4c88d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>1ba02b48-c25a-478c-8ef1-83dc9991fab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user[city_id]</value>
      <webElementGuid>c610bff6-0510-4d01-a0a9-5a7fc7c1bdf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_city_id</value>
      <webElementGuid>187db427-174f-4ecf-97d4-0e4ee4dbc786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Kota
Solo
Jogja
Jakarta
Bandung
Semarang</value>
      <webElementGuid>17d681e1-1d08-4069-b1aa-de31ba2b612c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_city_id&quot;)</value>
      <webElementGuid>48e52013-69da-44d4-8335-b86012f020d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='user_city_id']</value>
      <webElementGuid>d811496c-79ca-4008-82ae-e0358954bed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kota'])[1]/following::select[1]</value>
      <webElementGuid>d3b2be46-a985-494b-8e9f-92ee22a78c12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama'])[1]/following::select[1]</value>
      <webElementGuid>cb6ba398-5c3e-441b-9e1b-6eeb0bd2fa18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat'])[1]/preceding::select[1]</value>
      <webElementGuid>82b95001-5a3c-46f2-8d28-0ee37b6e93f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jl. Jalan II'])[1]/preceding::select[1]</value>
      <webElementGuid>bcc68747-e968-4596-b4e9-dec1760492ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>6140efbe-dffc-4c47-b5f6-c0ff40bd4ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'user[city_id]' and @id = 'user_city_id' and (text() = 'Pilih Kota
Solo
Jogja
Jakarta
Bandung
Semarang' or . = 'Pilih Kota
Solo
Jogja
Jakarta
Bandung
Semarang')]</value>
      <webElementGuid>910d5cb3-38d5-4064-8a76-09854dd9569e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
