<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih KotaSoloJogjaJakartaBandungSemarang</name>
   <tag></tag>
   <elementGuidId>fc820ee2-f8c3-446b-b388-cc666b7251ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_city_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='user_city_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f00f5d82-f8e9-4dd2-a143-ce37fd2d13e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select rounded-4 p-3</value>
      <webElementGuid>3535cedf-5176-46b2-8493-931d9740316e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>c6322419-4950-4c08-86bc-e963c1894699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user[city_id]</value>
      <webElementGuid>a2cd15c4-6bb7-4ee5-8a20-e5ad1a190eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_city_id</value>
      <webElementGuid>849eb7e1-cdec-4e6b-95ca-3cfbce389cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Kota
Solo
Jogja
Jakarta
Bandung
Semarang</value>
      <webElementGuid>8aeaa988-b648-467e-a67b-d877ec3e12d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_city_id&quot;)</value>
      <webElementGuid>27e27e18-b30b-4c35-a035-ccc097c96628</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='user_city_id']</value>
      <webElementGuid>07051598-84ba-4c8d-ac2b-25e4a8795bf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kota'])[1]/following::select[1]</value>
      <webElementGuid>b11cec06-3519-484d-b3fe-39b5f22083d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama'])[1]/following::select[1]</value>
      <webElementGuid>b9fb4177-47d0-46e8-9175-28316d3e0d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat'])[1]/preceding::select[1]</value>
      <webElementGuid>0c7005a1-c42f-4dfd-ae49-bdd8138df679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jl. Jalan II'])[1]/preceding::select[1]</value>
      <webElementGuid>7acabe6f-c3cc-44dc-a75f-136ec8ad234e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>69828dc4-cdae-4ee9-a5be-a5c6a95f3d7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'user[city_id]' and @id = 'user_city_id' and (text() = 'Pilih Kota
Solo
Jogja
Jakarta
Bandung
Semarang' or . = 'Pilih Kota
Solo
Jogja
Jakarta
Bandung
Semarang')]</value>
      <webElementGuid>165057a1-73bd-4b77-87c8-ae1f8d06e9ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
